- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.dnf:
       name: nodejs
       state: present

    - name: creating roboshop user
      ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       system: true
       home: /app

    - name: creating directory
      ansible.builtin.file:
       path:  /app 
       state: directory

    - name: download cataloguecode
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
       dest: /tmp/catalogue.zip

    - name: extract catalogue catalogue code
      ansible.builtin.unarchive:
       src: /tmp/catalogue.zip
       dest: /app
       remote_src: yes


       
