- name: mongodb
  become: yes
  hosts: mongodb                        #https://github.com/saivenkatuppu/ansible-roboshop.git
  tasks:
   - name: copy mongodb repo
     ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

   - name: installing the mongodb
     ansible.builtin.dnf:
       name: mongodb-org
       state: present       

   - name: starting and enable mongodb
     ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
   - name: allow remote connection
     ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

   - name: restart mongodb
     ansible.builtin.service:
      name: mongod
      state: restarted 
      
