- name: mongodb
  become: yes
  hosts: mongodb                        #https://github.com/saivenkatuppu/ansible-roboshop.git
  tasks:
    - name: copy mongodb repo
      ansible.builtin.copy:
      src: mongo.repo #source
      dest: vim /etc/yum.repos.d/mongo.repo
    - name: installing the mongodb
      ansible.builtin.dnf:
       - name: mongo         