- name: mysql configure
  hosts: mysql
  become: yes
  tasks:
  - name: install my sql
    ansible.builtin.dnf:
      name: mysql-server
      state: installed

  - name: start and enable my sql server
    ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
        