- name: shipping configure
  become: yes
  hosts: shipping
  tasks:
    - name: install maven
      ansible.builtin.dnf:
         name: maven
         state: installed


    - name: create directory
      ansible.builtin.file:
      path: /app
      state: directory


    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app
    
    - name: downloading shipping code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip
   
    - name: extract shipping code
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app 
        remote_src: yes


    - name: install maven dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app


