- name: user
  hosts: user
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodejs
      ansible.builtin.dnf:
       name: nodejs
       state: present

    - name: creating roboshop user
      ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       system: true
       home: /app

    - name: creating directory
      ansible.builtin.file:
       path:  /app 
       state: directory

    - name: download usercode
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
       dest: /tmp/user.zip

    - name: extract user user code
      ansible.builtin.unarchive:
       src: /tmp/user.zip
       dest: /app
       remote_src: yes

    - name: installing npm
      community.general.npm:
       path: /app
    - name: copy module
      ansible.builtin.copy:
       src: user.service
       dest: /etc/systemd/system/user.service

    - name: system daemon_reload
      ansible.builtin.systemd_service:
       daemon_reload: true
       

    - name: start and enable
      ansible.builtin.service:
       name: user
       state: started
       enabled: yes
